language : python
sudo : true

os:
    - linux

python :
    - "2.7"

before_install:
    - "pip install -U pip"
    - cd hello-example/
    - python setup.py install

branches:
    - master

script:
    - sudo python setup.py install
    - cd ../test/
    - ls
    - python test_hello_example.py
