language : python
sudo : true

os:
    - linux

python :
    - "2.7"

before_install:
    - "pip install -U pip"

branches:
    - master

script:
    - cd hello-example
    - sudo python setup.py install
    - cd ../test/
    - python test_hello_example.py
